/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v1/import-batches/preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Preview Import */
        post: operations["preview_import_v1_import_batches_preview_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Body_preview_import_v1_import_batches_preview_post */
        Body_preview_import_v1_import_batches_preview_post: {
            /** File */
            file?: string | null;
        };
        /** ErrorBody */
        ErrorBody: {
            /** Code */
            code: string;
            /** Message */
            message: string;
            /** Details */
            details: components["schemas"]["ErrorDetail"][];
        };
        /** ErrorDetail */
        ErrorDetail: {
            /** Field */
            field: string;
        };
        /** ErrorResponse */
        ErrorResponse: {
            error: components["schemas"]["ErrorBody"];
        };
        /** ImportPreviewResponse */
        ImportPreviewResponse: {
            /** Filename */
            filename: string;
            /** Checksum */
            checksum: string;
            /** Source */
            source: string;
            /** Totalcount */
            totalCount: number;
            /** Validcount */
            validCount: number;
            /** Invalidcount */
            invalidCount: number;
            /** Duplicatecount */
            duplicateCount: number;
            /** Records */
            records: components["schemas"]["PreviewRecordResponse"][];
        };
        /** PreviewRecordResponse */
        PreviewRecordResponse: {
            /** Rownumber */
            rowNumber: number;
            /** Classification */
            classification: string;
            /** Raw */
            raw: {
                [key: string]: string | null;
            };
            session?: components["schemas"]["SessionPreviewResponse"] | null;
            /** Errorfield */
            errorField?: string | null;
            /** Errorcode */
            errorCode?: string | null;
            /** Errormessage */
            errorMessage?: string | null;
        };
        /** SessionPreviewResponse */
        SessionPreviewResponse: {
            /** Chargerserial */
            chargerSerial: string;
            /**
             * Startedat
             * Format: date-time
             */
            startedAt: string;
            /**
             * Endedat
             * Format: date-time
             */
            endedAt: string;
            /** Energykwh */
            energyKwh: string;
            /** Chargeport */
            chargePort: number | null;
            /** Cardidraw */
            cardIdRaw: string | null;
            /** Identityconfidence */
            identityConfidence: string;
            /** Provenance */
            provenance: string;
            /** Deduplicationkey */
            deduplicationKey: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    preview_import_v1_import_batches_preview_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "multipart/form-data": components["schemas"]["Body_preview_import_v1_import_batches_preview_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImportPreviewResponse"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
}
