/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v1/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Me */
        get: operations["me_v1_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/import-batches/preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Preview Import */
        post: operations["preview_import_v1_import_batches_preview_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/import-batches": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Import Batches */
        get: operations["list_import_batches_v1_import_batches_get"];
        put?: never;
        /** Confirm Import */
        post: operations["confirm_import_v1_import_batches_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/import-batches/{batch_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Import Batch */
        get: operations["get_import_batch_v1_import_batches__batch_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Body_confirm_import_v1_import_batches_post */
        Body_confirm_import_v1_import_batches_post: {
            /** File */
            file?: string | null;
        };
        /** Body_preview_import_v1_import_batches_preview_post */
        Body_preview_import_v1_import_batches_preview_post: {
            /** File */
            file?: string | null;
        };
        /** ErrorBody */
        ErrorBody: {
            /** Code */
            code: string;
            /** Message */
            message: string;
            /** Details */
            details: components["schemas"]["ErrorDetail"][];
        };
        /** ErrorDetail */
        ErrorDetail: {
            /** Field */
            field: string;
        };
        /** ErrorResponse */
        ErrorResponse: {
            error: components["schemas"]["ErrorBody"];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** ImportBatchDetailResponse */
        ImportBatchDetailResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Filename */
            filename: string;
            /** Checksum */
            checksum: string;
            /** Source */
            source: string;
            /** Status */
            status: string;
            /** Created */
            created: boolean;
            /** Totalcount */
            totalCount: number;
            /** Validcount */
            validCount: number;
            /** Invalidcount */
            invalidCount: number;
            /** Duplicatecount */
            duplicateCount: number;
            /**
             * Createdat
             * Format: date-time
             */
            createdAt: string;
            /** Records */
            records: components["schemas"]["PersistedRawRecordResponse"][];
        };
        /** ImportBatchListResponse */
        ImportBatchListResponse: {
            /** Items */
            items: components["schemas"]["ImportBatchResponse"][];
        };
        /** ImportBatchResponse */
        ImportBatchResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Filename */
            filename: string;
            /** Checksum */
            checksum: string;
            /** Source */
            source: string;
            /** Status */
            status: string;
            /** Created */
            created: boolean;
            /** Totalcount */
            totalCount: number;
            /** Validcount */
            validCount: number;
            /** Invalidcount */
            invalidCount: number;
            /** Duplicatecount */
            duplicateCount: number;
            /**
             * Createdat
             * Format: date-time
             */
            createdAt: string;
        };
        /** ImportPreviewResponse */
        ImportPreviewResponse: {
            /** Filename */
            filename: string;
            /** Checksum */
            checksum: string;
            /** Source */
            source: string;
            /** Totalcount */
            totalCount: number;
            /** Validcount */
            validCount: number;
            /** Invalidcount */
            invalidCount: number;
            /** Duplicatecount */
            duplicateCount: number;
            /** Records */
            records: components["schemas"]["PreviewRecordResponse"][];
        };
        /** MeResponse */
        MeResponse: {
            /**
             * Profileid
             * Format: uuid
             */
            profileId: string;
            /**
             * Organizationid
             * Format: uuid
             */
            organizationId: string;
            role: components["schemas"]["OrganizationRole"];
            /** Unitid */
            unitId: string | null;
        };
        /**
         * OrganizationRole
         * @enum {string}
         */
        OrganizationRole: "manager" | "resident" | "technical_operator";
        /** PersistedRawRecordResponse */
        PersistedRawRecordResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Rownumber */
            rowNumber: number;
            /** Raw */
            raw: {
                [key: string]: string | null;
            };
            /** Classification */
            classification: string;
            /** Errorfield */
            errorField: string | null;
            /** Errorcode */
            errorCode: string | null;
            /** Errormessage */
            errorMessage: string | null;
            /** Sessionid */
            sessionId: string | null;
        };
        /** PreviewRecordResponse */
        PreviewRecordResponse: {
            /** Rownumber */
            rowNumber: number;
            /** Classification */
            classification: string;
            /** Raw */
            raw: {
                [key: string]: string | null;
            };
            session?: components["schemas"]["SessionPreviewResponse"] | null;
            /** Errorfield */
            errorField?: string | null;
            /** Errorcode */
            errorCode?: string | null;
            /** Errormessage */
            errorMessage?: string | null;
        };
        /** SessionPreviewResponse */
        SessionPreviewResponse: {
            /** Chargerserial */
            chargerSerial: string;
            /**
             * Startedat
             * Format: date-time
             */
            startedAt: string;
            /**
             * Endedat
             * Format: date-time
             */
            endedAt: string;
            /** Energykwh */
            energyKwh: string;
            /** Chargeport */
            chargePort: number | null;
            /** Cardidraw */
            cardIdRaw: string | null;
            /** Identityconfidence */
            identityConfidence: string;
            /** Provenance */
            provenance: string;
            /** Deduplicationkey */
            deduplicationKey: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    me_v1_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeResponse"];
                };
            };
        };
    };
    preview_import_v1_import_batches_preview_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "multipart/form-data": components["schemas"]["Body_preview_import_v1_import_batches_preview_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImportPreviewResponse"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    list_import_batches_v1_import_batches_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImportBatchListResponse"];
                };
            };
        };
    };
    confirm_import_v1_import_batches_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "multipart/form-data": components["schemas"]["Body_confirm_import_v1_import_batches_post"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImportBatchResponse"];
                };
            };
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImportBatchResponse"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    get_import_batch_v1_import_batches__batch_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                batch_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImportBatchDetailResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
}
